language: php

cache:
  directories:
    - $HOME/.composer/cache/files
env:
  matrix:
    - php: 7.2
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*' COMPOSER_FLAGS='--prefer-stable'
    - php: 7.2
      env: LARAVEL='^6.0' TESTBENCH='^4.0' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
      env: LARAVEL='^6.0' TESTBENCH='^4.0' COMPOSER_FLAGS='--prefer-stable'
    - php: 7.3
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*' COMPOSER_FLAGS='--prefer-stable'
    - php: 7.3
      env: LARAVEL='^6.0' TESTBENCH='^4.0' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3
      env: LARAVEL='^6.0' TESTBENCH='^4.0' COMPOSER_FLAGS='--prefer-stable'
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4snapshot
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*' COMPOSER_FLAGS='--prefer-stable'
    - php: 7.4snapshot
      env: LARAVEL='^6.0' TESTBENCH='^4.0' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4snapshot
      env: LARAVEL='^6.0' TESTBENCH='^4.0' COMPOSER_FLAGS='--prefer-stable'

before_install:
  - composer config discard-changes true
  - travis_retry composer self-update
  - travis_retry composer require --dev "laravel/framework:${LARAVEL}" --no-interaction --no-update
  - travis_retry composer require --dev "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update
  - travis_retry composer require --dev scrutinizer/ocular --no-interaction --no-update
  - travis_retry composer require --dev php-coveralls/php-coveralls --no-interaction --no-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-suggest --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/clover.xml

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/clover.xml
  - php vendor/bin/php-coveralls
