language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - travis_retry composer require --dev scrutinizer/ocular --no-interaction
  - travis_retry composer require --dev php-coveralls/php-coveralls --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/clover.xml
  - php vendor/bin/php-coveralls
